#+TITLE: nndl lesson 11

* Intro
Thus a neural network composed of just 1 hidden layer, with activation function non linear and not polinomual is a /universal approximator/, so the network organization is:
1. $d$ input values
2. $m$ hidden neurons, with non polynomial activation function
3. $c$ output neurons
4. $W_1$, $m \times d$ weight matrix from input values to the hidden neurons
5. $B_1$, $m \times 1$ bias column vector of the $m$ hidden neurons
6. $W_2$, $c \times m$ weight matrix (from hidden layer to output neurons)
7. $B_2$, $c \times 1$ bias column vector of the $c$ output neurons
** The problem
1. find the correct number
2. find activation function
3. find $W_1$, $W_2$, $B_1$, $B_2$
* Vanilla Networks
In this case we have a /MLNN/ with two neuron layers or two weight layer.
This type of neural networks are currently /vanilla networks/.
$m$ and $g$ are said hyperparameters of the network, $W_1, W_2, B_1, B_2$ parameters of the networks.
Usually a learning process involves, changes the parameters. From now on we focus on the way to find the /correct/ parameters.
* Find the parameters
In order to find the parameters we need:
** Dataset
A dataset composed of $N$ pairs ~{x^n, t^n}~, with $n = 1, \cdots N$.
$x^n$ belongs to $R^d$, $t$ (said target) belongs to $R^c$, $t^n$ represent the expected value when one has $x^n$ as input.
Note:
+ In the case of classification problem $t^n$ is a discrete variable (*label*).
+ In the case of regression problem $t^n$ is a continue variable.
** Error function
A way to meausere the accurancy of the neural network response (*error function*).
This function told us how the network (with certain fixed weight) is responding well on the dataset.
For example in the case of regression problem we have:
$\sum_{n=1}^N \frac 1 2 \sum_{k=1}^c (y^{n_k}- t^{n_k})^2$ where $y^{n_k}$ is the output values of the /k-th/ output neuron when the network receives as input $x^n$, $t^n$ is the /k-th/ component of the /n-th/ target value.
Note that $y^n$ value depends on the network parameters, so we can view as $y^{n_k}=y_k(x^n, \theta)$, $\theta$ are all the network parameters.
Thus if we leave fixed the dataset and the network architecture $(m,g)$ the error depends only on the network parameters, for this reason we say *error function*, it is a function of the network parameters.
$$E=E(\theta)$$
*** Note
The error on the output is misured with the *euclidean distance* from the result vector and the expected result.
*** Our goal
Our goal is to minimize $E$ with respect $\theta$.
But how we can minimize such error?
We want to find the minimum, there can be more than one in such case we want to find the /absolute/ minimum.

A learning algorithm (process) correspond to the /operations/ to find this minimum.
In the case of a neural network the learning process corresponds to:

Use an iterative approach

To each iteration we want to know if the error function is increasing or decreasing with respect the parameters, so we need to find the partial derivatives of the error functions with respect the weights $w_{ij}$ and the biases $b_i$.
$$\frac {\delta E} {\delta W_{ij}}}$$
** Standard gradient descend
See back propagation.
