:PROPERTIES:
:ID:       dec0d1f1-5ca7-421f-9178-96e5669e6bdf
:END:
#+title: Architecture Design
#+filetags: :architecture:design:engineering:pattern:

* What does it do?
In this phase the engineers produce a model (*architectural model*) that show how the software will be organized in modules.
They may be multiple models with differents level of details.
If the model is not well engineered then they may be some refactoring in the architecture later on, these kind of refactoring are *very expensive*.
* Level of Abstractions
+ Little:
    How each component interacta and also how it is splitted into others component, this type is the one that will represent the best the final product (in term of code).
+ Big:
    Show how the system is splitted into big components, this is more abstract.
* Architectural choices to make
+ There are some trades to make during the design process, these trades depends on the requirements of the project
+ There are also some /style/ that impose a structure on the design, like [[id:bb15c95e-f558-4939-bd88-1fd328e92f6b][Client Server]] or P2P
The design process can be seen as a sequence of choice to make that will shape the final product, just like in algorithmic you may have to choose between trees and maps based on your problem (spoiler maps wins almost all the time).
** Trades based on the properties
*** Performance
If the performance are critical to the system you may have to install all the components on the same machine to avoid exchanging messages between different machines.
This approach reduce the /maintainability/.
*** Protection
In this case an architecture based on layers, where to most important ones have to be in the lowest tier (or the inner most if you prefer circles).
*** Security
In this case all the operations related to security should be confined in a single component and should be well tested to ensure the functionality.
This slightly reduce /maintainability/ and increase the /develop time/.
*** Availability (of resources)
You should consider how to duplicate the interested resources and how distribute them to accomodate the requests.
*** Maintainability
Each component should be independent off the others and should be interchangeable with some others.
Decrease the /performances/.

* Architectural Views
+ Logic:
  + show the keys abstractions
  + show relation between requirements and entity)
  + can be used to interact with the stakeholders
+ Process/Runtime:
  + show how at runtime the system works
  + used to analyze the non-functional requirements of the system
+ Develop:
  + show how the software is splitted in components/modules
  + useful for the programmers to implement the software
  + useful for the software managers to analyze the project
+ Physic:
  + show how the hardware and the components are deployed and configured
* Architectural Scheme
Common technique to produce more robust and reusable code, also known as /Design Patterns/.
** Some common patterns/schemes
+ [[id:1fdede00-97e0-404d-b605-3eb407cd8620][MVC]]
+ [[id:5a4d0c74-a133-4915-96fe-e97a36dc1561][Layer]]
+ [[id:213bf04b-fc62-4420-89db-ddd6491922d4][Repository]]
+ [[id:bb15c95e-f558-4939-bd88-1fd328e92f6b][Client Server]]
+ [[id:db905660-a0c8-49f9-8b7f-4c03ec5aedb9][Pipe and Filter]]
