:PROPERTIES:
:ID:       044cbe89-4577-45b8-abfd-b3797e23208f
:END:
#+title: Hash Files
#+filetags: :hashing:database:files:

* Hash File approach
#+begin_center
Instead of maintaining an [[id:df0f92d7-7e9b-4b61-9cf8-7b79808e20dd][Heap Files]] we can use an ~hash function~ on the fields.
This increase the usage of the memory and some of the operations.
#+end_center
** Note
We can resolve *collision* both by *chaining* or by *open addressing*.
* Performance
Assuming we have a good hash function we have.
** Insertion
$$T_{insertion} = O(1)$$
** Search
$$T_{search} = O(k)$$
Where $k$ is the length of the list or probing sequence, ideally $k \sim O(1)$.
** Delete
$$T_{delete} = O(k) \sim O(1)$$
** Modify
A modify may change the key upon we hash so we must remove the element, update and the reinsert.
$$T_{modify} = O(k) \sim O(1)$$
* What we can say about ordered and set operation
With hash files all such data will be sparse hence all the good point of an hash file will be annihilate in this case, we are forced to do a linear scan of *ALL* data, implying and $O(n)$.
* Fixed Address Space
Since the space to which we map the data is fixed, hash files will full that space, when this happens we can use one of following approach:
+ extensible hash
+ dynamic hash
+ linear hash
* [[id:83306108-1751-447e-9b45-918b23054863][Cost Models]]
From empirical studies it is shown that, usually, the key value pair takes $\frac 1 10$ of record's size.
For simplicity we are assuming that we are working with static hashing, where pages are kept $80\%$ full, thus the number of pages required is $1.25$ more than normal, hence $1.25(0.1B) = 0.125B$
The number of data entries in a page is $10(0.8R)= 8R$
** Scan
We have to scan the whole file, unfortunately this can be done only using the /hash function/.
$$0.125B(D + 8RC)$$
The cost in this case is prohibitive.
** Search
The search is cheap, we use the hash function with cost $H$ then we read the page and find the record, remember that also the /hash page/ must be read in time $D$.
$$H + 2D + 8RC$$
On average we permorm only half of the read on the file hence
$$H + 2D + 4RC$$
** Search with range
Since there is no order we must scan the whole file.
$$0.125B(D + 8RC)$$
** Insertion
We need to find the page and the add the record in time $C$, we don't need to process other data.
$$H + 2D + C$$
** Deletion
First we have to search for the record and then remove it, this basically reduce it to the cost of a search.
$$H + 2D + 4RC$$
