:PROPERTIES:
:ID:       df0f92d7-7e9b-4b61-9cf8-7b79808e20dd
:ROAM_ALIASES: "Unordered Files"
:END:
#+title: Heap Files
#+filetags: :database:files:

* How they work
This is the simples approach:
#+begin_center
Each new record is put at the end of the file.
With this approach we fill every block progressively.
All the blocks, except the last one, are full.
#+end_center
* Performance
** Insertion
$$T_{insertion} = O(1)$$
** Search
We must do a linear scan over the blocks until we visit the right one and then scan the block for the data.
$$T_{search} = O(n)$$
*** More formally
$N =$ number of records.
$R =$ number of records that can be stored in a block.
$n = \frac N R$ number of blocks needed.
The complexity is the average of all cases:
$$\frac {R \cdot 1 + R \cdot 2 + \cdots + R \cdot n} N$$
Which is equal to:
$$\frac {R \cdot \sum_{i=1}ˆn i} N$$
$$\frac R N \cdot \frac {n (n+1)} 2$$
But we know that:
$n = \frac N R$ so $R = \frac N n$
So we can conclude:
$$\frac {n (n + 1)} {2n} \sim \frac n 2$$
** Update/Modify
First we have to search for the data, hence an $O(n)$, and then write the data back.
$$T_{modify} = O(n)$$
** Delete
This is tricky since when we delete a block we leave an empty spot.
Fill that spot require a shifting on all data and that is expensive.
A different solution is mark the spot as deleted and when we compact the data we can remove the hole, like in *open addressing* [[denote:20230930T124136][Hash Table]].
$$T_{delete} = O(n)$$
** Set operation
The operation that return a set of record all require an $O(nˆ2)$, except for insertion.
* What if we order the heap?
We will have a slowdown on *insertion* and some spedup on *search* but the order is to expensive to maintain, furthermore when we search for a field that is not included in *comparison method* used to sort we have the same performance of an unorderd one.
* [[id:83306108-1751-447e-9b45-918b23054863][Cost Models]]
** Unordered heap file
*** Scanning
If the search field is not unique
$$B(D+RC)$$
That because we have to retrieve each of the $B$ pages taking a time $D$ for each page.
For each block we have to process $R$ records taking time $C$ for each.

If the search field is known to be uninque, on average, it takes
$$\frac {B(D+RC)} 2$$

If the search field is not present, we have to scan the whole file
$$B(D+RC)$$
*** Search
Since there is no order we have to scan the whole file each time
$$B(D+RC)$$
*** Insertion
Insertion is cheap because we just have to append to the end of the file.
$2D + C$
One $D$ for read the file, $C$ to process the new record and append to the file, at last the second $D$ to write the files back onto the file.
*** Deletion
For simplicity that no action is take to compact the file.
First we need to search for the record, since it is unique this require
$\frac {B(D+RC)} 2$.
Then we have to remove the record with cost $C$ and write everything back with $D$.
The total is:
$$\frac {B(D+RC)} + C + D2$$
** Ordered Heap files
*** Scanning
Like in the unordered one we have to visit the whole file.
$$B(D + RC)$$
*** Search
Here I'm assuming the search on the sort field.
We can locate the desired page with $\log_2(B)$, each load cost $D$, search, then we can do another binary search to find the desired block among the ones loaded, each inspected block cost $C$.
$$D\log_2(B) + C\log_2(R)$$
*** Search with range
In the worst case, once we have found the first element we may to scan the whole page.
$$D\log_2(B) + RC$$
*** Insertion
This one is expensive because we first have to perform a search to understand in which spot we must put the file, then we have to rewrite the whole page to maintain the order
$$D\log_2(B) + C\log_2(R) + B(D+RC)$$
On average we move half of the elements but since we have to do a read and a write our operation to maintain the order are doubled, this factors out the $\frac 1 2$.
*** Deletion
Same thing as the insertion.
$$D\log_2(B) + C\log_2(R) + B(D+RC)$$
