#+title:      [DB tech] Hash Files
#+date:       [2023-09-30 Sat 21:58]
#+filetags:   :algorithm:course:database:study:
#+identifier: 20230930T215849

* Hash File approach
#+begin_center
Instead of maintaining an [[denote:20230930T214702][Heap files]] we can use an ~hash function~ on the fields.
This increase the usage of the memory and some of the operations.
#+end_center
** Note
We can resolve *collision* both by *chaining* or by *open addressing*.
* Performance
Assuming we have a good hash function we have.
** Insertion
$$T_{insertion} = O(1)$$
** Search
$$T_{search} = O(k)$$
Where $k$ is the length of the list or probing sequence, ideally $k \sim O(1)$.
** Delete
$$T_{delete} = O(k) \sim O(1)$$
** Modify
A modify may change the key upon we hash so we must remove the element, update and the reinsert.
$$T_{modify} = O(k) \sim O(1)$$
* What we can say about ordered and set operation
With hash files all such data will be sparse hence all the good point of an hash file will be annihilate in this case, we are forced to do a linear scan of *ALL* data, implying and $O(n)$.
* Fixed Address Space
Since the space to which we map the data is fixed, hash files will full that space, when this happens we can use one of following approach:
+ extensible hash
+ dynamic hash
+ linear hash
