#+title:      Stack
#+date:       [2023-09-30 Sat 12:53]
#+filetags:   :algorithm:datastructure:math:programming:
#+identifier: 20230930T125307

* Stack
A fundamental data structure used on all level of computer science, from hardware, to programming language, to software, to theoretical computer science.
* Definition
Basically it is a [[denote:20230930T124219][List]] with special rule for adding and removing element.
+ It is possible to add element only on the head.
+ It is possible to remove element only on the head
This create a LIFO (Last In First Out) structure
#+begin_src c
typedef struct node {
    struct node* next;
    type value;
}* node;

typedef struct stack {
    struct node* head;
    // others optional
    // size
    // etc...
}* stack;
#+end_src
* Operations
** Push element
#+begin_src c
void push(stack s, type element){
    node newnode = malloc(type);
    newnode->value = element;
    newnode->next = s->head;
    s->head = newnode
}
#+end_src
** Pop element
#+begin_src c
type pop(stack* s){
    if((*s)->head == NULL){
        //raise error
    }
    node tmp = (*s)->head;
    (*s)->head = (*s)->head->next;
    type value = (*s)->head->value;
    return value;
}
#+end_src
** Top element
#+begin_src c
type top(stack s){
    if(s->head == NULL){
        //raise error
    }
    return s->head->value;
}
#+end_src
* Properties
+ Inherited from list.
+ LIFO
* Extension
** Min Stack
This extension contains an inner stack that contains, on the top, the minimum value in the stack.

The secondary stack, the one for the minimum values, need to push a new value only when the new value to add is smaller than the one on top.
The element on top is removed only when the element on top is removed from the main stack.
* Time complexity
| operation | time complexity |
|-----------+-----------------|
| push      | $O(1)$          |
| pop       | $O(1)$          |
| top       | $O(1)$          |
