#+title:      Sorting
#+date:       [2023-09-30 Sat 12:29]
#+filetags:   :algorithm:math:programming:sorting:
#+identifier: 20230930T122917

* Sorting
A class of algorithm which main focus is order a sequence of value given an ~order relationship~.
* Lower Bound and Average Bound (Sorting based on comparison)
This section apply only to the comparison based on comparison.
** Comparison Tree
In this type of tree each node contains the comparison made and each edge to the children represent the result of the comparison.
The only nodes that not contains a comparison operation are the leafs, each leaf represent one of the possible rearrangement of the input sequence.

+ They are Binary Tree (at most two child)
+ Since for an input sequence of $size = n$ there are $n!$ possible rearrangement, so there are $n!$ leaves.
+ For all sorting algorithm exist a comparison tree that model its behavior.
+ Find a lower bound for all the comparison tree means that we find a lower bound to the problem of sorting.
+ Same apply for the /average bound/.
+ The path from the root to a leaf indicates the /swaps/ to do order the input.
+ The height of a comparison tree is equal to the time complexity of the tree that it represent.
** Lower Bound
A binary tree of
$$height = h$$
has at most
$$numberOfChildren = 2^h$$

We also know that for a comparison tree for a sequence of
$$size=n$$
the tree has
$$leafs = n!$$

So we can Say
$$n! \le 2^h$$
$$\log_2{n!} \le h$$

We can approximate $n!$ with the [[https://en.wikipedia.org/wiki/Stirling%27s_approximation][Stirling approximation]].
Or we could reason with the following derivation.

$$\log {n!} = \log{\prod_{i=1}^n i}$$
$$\log{\prod_{i=1}^n i} = \sum_{i=1}^n\log i$$

Using the following overcount
$$\sum_{i=1}^n\log i \le \sum_{i=1}^n\log n$$
$$\sum_{i=1}^n\log n = n \log n$$

So we can conclude that
$$h \ge n \log n$$

Hence a comparison sorting algorithm in the worst case can't be better than
$$\Omega(n \log n)$$
*** With Stirling approximation
$$n! \sim {\frac n e}^n$$
$$\log{n!} \sim \log{\frac n e}^n$$
$$\log{n!} \sim n\log n$$
$$\log{n!} = \Theta(n\log n)$$
** /Average Bound/
To find this bound we need the /external path/.
*** Definition of external path /EP/
It is the sum of the length of each path from the root to a leaf.

+ With this we can compute $averageBound = \frac{EP}{n!}$
*** Minimize the EP
+ Minimize the EP correspond to minimize the number of comparison from the root to a leaf.

The type of tree that minimize the height is /complete tree/
+ In a complete tree each internal node has 2 child with the exception that only one node can have 1 child
+ The leaf are all the $height = h$ or $height = h - 1$
**** The complete tree is the best choice? (Proof)
Proof by contraddiction.
Assume that the complete tree, with $externalPath = EP$, is not the best choice.

Move 2 children from a leaf to another leaf at the maximum height, the external path has changed.
Let's see how it's changed.

$$EP' = EP - 2h + (h-1) - h + 2(h+1)$$
$$EP' = EP + 1$$
$$\blacksquare$$
**** Compute the EP on complete tree
In a complete tree with $n!$ leaf and $height = h$ we have that all the leaf are at $height = h$ or $height = h - 1$.
With $N_h$ we indicate the leaf at $height = h$ and with $N_{h-1}$ the leaf at $height = h - 1$.
So the EP is:
$$EP = h \cdot N_h + (h-1) \cdot N_{h-1}$$
$$EP = h \cdot (N_h + N_{h-1}) - N_{h-1}$$

We observe that:
$$N_h + N_{h-1} = n!$$
This because it is still a comparison tree.

We need to find $N_{h-1}$.
We know that to fill complete tree into /full tree/ we need to double the number of leaf at $height = h - 1$, hence we need $2 \cdot N_{h-1}$ leafs.
$$2^h = N_h + 2N_{h-1}$$
We can create a system of equation now:
$$
\begin{equation}
  \begin{cases}
    2^h = N_h + 2N_{h-1}, & \text{if $n \le 1$}.\\
    n! = N_h + N_{h-1}, & \text{otherwise}.
  \end{cases}
\end{equation}
$$
Applying a subtraction by column we get:
$$2^h - n! = N_h + 2N_{h-1} - N_h - N_{h-1}$$
$$2^h - n! = N_{h-1}$$
We have found $N_{h-1}$!
$$EP = h\cdot N_h + (h-1) \cdot (2^h - n!)$$
$$EP = n!(h + 1) - 2^h$$
$$EP = h\cdot n! + n! - 2^h$$

With we can proceed to compute the average bound.
$$\frac{EP}{n!} = \frac{h\cdot n! + n! - 2^h}{n!}$$

This resolve to:
$$\frac{EP}{n!} = h - \frac{2^h}{n!} + 1$$
This is our formula to get the average bound.

Now in a complete tree we also know that:
$$height = \log{numberOfLeaf}$$
$$height = \log{n!}$$

Inserting that in the formula for the average bound and we get:
$$\frac{EP}{n!} = \log{n!} - \frac{2^{\log{n!}}}{n!} + 1$$
$$\frac{EP}{n!} = n\log{n} - \frac{n!}{n!} + 1$$
$$\frac{EP}{n!} = n\log{n} - 1 + 1$$
$$\frac{EP}{n!} = n\log{n}$$
$$\frac{EP}{n!} = \Theta(n\log{n})$$

The average bound for the sorting problem, based on comparison, is:
$$\Theta(n\log n)$$
$$\blacksquare$$
